server {
    listen 80;
    server_name _;

    location = /.well-known/appspecific/com.tesla.3p.public-key.pem {
        root /usr/share/nginx/html;
        default_type application/x-pem-file;
        add_header Cache-Control "public, max-age=3600";
    }

    location / {
        return 404;
    }
}
